// Short ideas worth knowing, one shown after each puzzle: long enough to be useful, short
// enough to read before the next stop. Written in our own words. Each names where the
// idea comes from, and hedges where the research is weaker than the popular version.

export type Topic = 'psychology' | 'software' | 'philosophy' | 'productivity';

export const TOPICS: { id: Topic; name: string }[] = [
  { id: 'psychology', name: 'Psychology' },
  { id: 'software', name: 'Software engineering' },
  { id: 'philosophy', name: 'Philosophy' },
  { id: 'productivity', name: 'Productivity' },
];

export interface Knowledge {
  id: string;
  topic: Topic;
  title: string;
  body: string;
  /** Something to do with it today. */
  tryThis: string;
}

export const KNOWLEDGE: Knowledge[] = [
  // ---------- Psychology ----------
  {
    id: 'spacing-effect',
    topic: 'psychology',
    title: 'The spacing effect',
    body: 'Practice spread over several days is remembered far longer than the same amount crammed into one sitting. Reviewing just as something starts to fade is what makes it stick.',
    tryThis: "Look back at today's chapter tomorrow, then again in a week.",
  },
  {
    id: 'testing-effect',
    topic: 'psychology',
    title: 'Retrieval beats rereading',
    body: 'Pulling an idea out of memory strengthens it more than reading it again, even when the recall is slow and patchy. Rereading feels productive because it is familiar, not because it works.',
    tryThis: 'Close the book and say the three main points of what you just read.',
  },
  {
    id: 'generation-effect',
    topic: 'psychology',
    title: 'The generation effect',
    body: 'Information you produce yourself, even a wrong guess that gets corrected, is remembered better than information you only read. Effort at the moment of learning pays off later.',
    tryThis: 'Before reading a section, guess what it will say.',
  },
  {
    id: 'feynman',
    topic: 'psychology',
    title: 'Explain it simply',
    body: 'Explaining an idea in plain words, as if to a beginner, exposes the gaps you skipped over. Where you reach for jargon is usually where your understanding stops.',
    tryThis: "Explain one idea from your book to a friend who hasn't read it.",
  },
  {
    id: 'sleep-memory',
    topic: 'psychology',
    title: 'Sleep files your memories',
    body: 'During sleep the brain replays and strengthens what was learned that day. Studying late and then sleeping well beats staying up late to study more.',
    tryThis: 'Review what matters most shortly before bed.',
  },
  {
    id: 'cognitive-load',
    topic: 'psychology',
    title: 'Working memory is small',
    body: 'We can hold only about four chunks of new information in mind at once. Experts cope by grouping many details into one familiar chunk.',
    tryThis: 'Break anything you need to remember into groups of three or four.',
  },
  {
    id: 'attention-residue',
    topic: 'psychology',
    title: 'Attention residue',
    body: 'When you switch tasks, part of your attention stays behind on the last one, especially if it was left unfinished. Frequent switching leaves you working with a fraction of your mind.',
    tryThis: 'Batch messages into two or three set times instead of checking constantly.',
  },
  {
    id: 'implementation-intentions',
    topic: 'psychology',
    title: 'When–then plans',
    body: 'Plans phrased as "when X happens, I will do Y" make people much more likely to follow through than a general intention. The cue does the remembering for you.',
    tryThis: 'Write one: "When I sit down on the train, I will read ten pages."',
  },
  {
    id: 'zeigarnik',
    topic: 'psychology',
    title: 'Unfinished business',
    body: 'Unfinished tasks tend to keep nagging at the mind (the Zeigarnik effect, though later studies are mixed). Writing down the next step seems to quiet the nagging and makes restarting easier.',
    tryThis: 'End each work session by noting exactly what to do first next time.',
  },
  {
    id: 'planning-fallacy',
    topic: 'psychology',
    title: 'The planning fallacy',
    body: 'We underestimate how long our own tasks will take, even when we know similar tasks ran late before. Imagining the steps makes us optimistic; looking at past cases makes us accurate.',
    tryThis: 'Estimate from how long the last similar task actually took.',
  },
  {
    id: 'peak-end',
    topic: 'psychology',
    title: 'The peak–end rule',
    body: 'We remember an experience mostly by its most intense moment and by how it ended, not by its average or its length (Kahneman). A good ending can redeem a long, dull middle.',
    tryThis: 'Finish meetings and study sessions on something that went well.',
  },
  {
    id: 'loss-aversion',
    topic: 'psychology',
    title: 'Loss aversion',
    body: 'A loss feels roughly twice as strong as a gain of the same size (Kahneman and Tversky). It makes us cling to the status quo and turn down bets that are actually good.',
    tryThis: 'Ask whether you are avoiding a loss or chasing a better outcome.',
  },
  {
    id: 'anchoring',
    topic: 'psychology',
    title: 'Anchoring',
    body: 'The first number we hear pulls our estimates towards it, even when it is obviously arbitrary. Negotiators and price tags use this on purpose.',
    tryThis: 'Write down your own estimate before hearing anyone else’s.',
  },
  {
    id: 'confirmation-bias',
    topic: 'psychology',
    title: 'Confirmation bias',
    body: 'We notice, seek out and remember evidence that supports what we already believe, and discount the rest. Smart people are not immune; they are better at finding reasons.',
    tryThis: 'For a belief you hold, ask what evidence would change your mind.',
  },
  {
    id: 'attribution-error',
    topic: 'psychology',
    title: 'The fundamental attribution error',
    body: "We explain other people's behaviour by their character, but our own by our circumstances. The driver who cut you off is a jerk; when you do it, you were late.",
    tryThis: 'Next time someone annoys you, think of one situation that could explain it.',
  },
  {
    id: 'dunning-kruger',
    topic: 'psychology',
    title: 'Knowing what you don’t know',
    body: 'In the Dunning–Kruger studies the weakest performers overestimated themselves the most, partly because judging skill takes the same skill. The popular version exaggerates it, but the humility lesson holds.',
    tryThis: 'Ask someone more skilled to rate your work before you rate it yourself.',
  },
  {
    id: 'hedonic-adaptation',
    topic: 'psychology',
    title: 'Hedonic adaptation',
    body: 'After most gains and losses, happiness drifts back towards where it was. New things stop feeling new; variety and gratitude slow the fade.',
    tryThis: 'Notice one thing you have grown used to and would miss if it were gone.',
  },
  {
    id: 'spotlight-effect',
    topic: 'psychology',
    title: 'The spotlight effect',
    body: 'People notice our mistakes and appearance far less than we think (Gilovich). Everyone is mostly busy with their own spotlight.',
    tryThis: 'Try the thing you are putting off because it might look awkward.',
  },
  {
    id: 'flow',
    topic: 'psychology',
    title: 'Flow',
    body: 'Deep absorption tends to come when a task is just beyond your current skill, the goal is clear and feedback is immediate (Csikszentmihalyi). Too easy is boring; too hard is anxious.',
    tryThis: 'Make a dull task harder, or a daunting one smaller, until it grips you.',
  },
  {
    id: 'fresh-start',
    topic: 'psychology',
    title: 'The fresh start effect',
    body: 'People are more likely to begin new goals on dates that feel like new beginnings: a Monday, a birthday, the first of the month. The date changes nothing, but the story does.',
    tryThis: 'Pick a near "fresh start" day for a habit you keep postponing.',
  },

  {
    id: 'interleaving',
    topic: 'psychology',
    title: 'Mix it up',
    body: 'Practising different kinds of problems shuffled together feels harder than doing one kind at a time, but it teaches you to recognise which method each problem needs, and the learning lasts longer.',
    tryThis: 'Shuffle the exercises from two chapters instead of doing them in order.',
  },
  {
    id: 'desirable-difficulties',
    topic: 'psychology',
    title: 'Desirable difficulties',
    body: 'Robert Bjork found that conditions which slow learning down, like spacing, mixing and testing yourself, often make it last. Smooth, easy study tends to feel better than it works.',
    tryThis: 'When studying feels effortless, make it harder: test yourself.',
  },
  {
    id: 'availability',
    topic: 'psychology',
    title: 'The availability heuristic',
    body: 'We judge how common something is by how easily examples come to mind (Tversky and Kahneman). Vivid news makes plane crashes feel likelier than car crashes, though they are far rarer.',
    tryThis: 'Before judging a risk, look up how often it actually happens.',
  },
  {
    id: 'defaults',
    topic: 'psychology',
    title: 'The power of defaults',
    body: 'Whatever happens if you do nothing wins surprisingly often. Countries where organ donation is the default have far higher sign-up rates than countries where people must opt in.',
    tryThis: 'Change one default in your life: move the app, pre-pack the bag.',
  },
  {
    id: 'sunk-cost',
    topic: 'psychology',
    title: 'The sunk cost fallacy',
    body: "Time or money already spent can't be recovered, yet it makes us keep going with things we'd never start today. Only future costs and benefits should count.",
    tryThis: 'Ask of one commitment: would I start this today, knowing what I know?',
  },
  {
    id: 'mere-exposure',
    topic: 'psychology',
    title: 'The mere exposure effect',
    body: 'People tend to like things more simply because they have seen them before (Zajonc). Familiarity is easily mistaken for quality or truth.',
    tryThis: 'Notice whether you like an idea, or have just heard it often.',
  },
  {
    id: 'ikea-effect',
    topic: 'psychology',
    title: 'The IKEA effect',
    body: 'We value things more when we have built them ourselves, even badly (Norton, Mochon and Ariely). It is why our own plans and code look better to us than to others.',
    tryThis: 'Ask someone else to judge the thing you made.',
  },
  {
    id: 'hindsight-bias',
    topic: 'psychology',
    title: 'Hindsight bias',
    body: 'Once we know how something turned out, we believe we saw it coming. It makes past decisions look obviously right or wrong and hides how uncertain they were.',
    tryThis: 'Write down your prediction before you learn the outcome.',
  },
  {
    id: 'survivorship-bias',
    topic: 'psychology',
    title: 'Survivorship bias',
    body: "Looking only at what survived misleads. In the Second World War, Abraham Wald saw that returning bombers' bullet holes showed where planes could be hit and still fly home.",
    tryThis: 'When studying success stories, ask who tried the same and failed.',
  },
  {
    id: 'regression-mean',
    topic: 'psychology',
    title: 'Regression to the mean',
    body: 'An unusually good or bad result is usually followed by a more ordinary one, whatever you do. It can make criticism seem to work and praise seem to backfire.',
    tryThis: 'Judge a change by many results, not the one right after it.',
  },
  {
    id: 'choice-overload',
    topic: 'psychology',
    title: 'Too many choices',
    body: 'In a famous study, shoppers offered 24 jams bought less often than those offered 6. Later studies find the effect only sometimes, but a short list does make choosing easier.',
    tryThis: 'Narrow a decision to three options before you compare them.',
  },
  {
    id: 'habits-context',
    topic: 'psychology',
    title: 'Habits live in context',
    body: 'Roughly 40% of daily actions are done out of habit, triggered by the place and time more than by intention (Wendy Wood). Change the setting and habits change with it.',
    tryThis: 'Make a good habit easy to start where you already are.',
  },
  {
    id: 'temptation-bundling',
    topic: 'psychology',
    title: 'Temptation bundling',
    body: 'Pair something you want to do with something you should do, like audiobooks only at the gym. Katherine Milkman found it got people exercising more.',
    tryThis: 'Pick one treat and allow it only during a task you avoid.',
  },
  {
    id: 'yerkes-dodson',
    topic: 'psychology',
    title: 'Just enough pressure',
    body: "Performance tends to rise with arousal up to a point, then fall (the Yerkes–Dodson law, a simplification of a 1908 study). A little tension sharpens you; panic doesn't.",
    tryThis: 'Before a big moment, breathe slowly to bring your pulse down.',
  },
  {
    id: 'social-proof',
    topic: 'psychology',
    title: 'Social proof',
    body: 'When unsure, we copy what others do (Cialdini). Hotel guests reused towels more when told most guests in their room had done the same.',
    tryThis: "Check whether you're doing something because it's right or because others do.",
  },
  {
    id: 'reciprocity',
    topic: 'psychology',
    title: 'Reciprocity',
    body: 'People feel a strong urge to return favours, even small, unasked-for ones (Cialdini). Free samples and gifts work because of it.',
    tryThis: 'Help someone first, without expecting anything back.',
  },
  {
    id: 'foot-in-door',
    topic: 'psychology',
    title: 'Foot in the door',
    body: 'Agreeing to a small request makes people likelier to agree to a bigger one later, because they come to see themselves as the kind of person who helps (Freedman and Fraser).',
    tryThis: 'Start a new habit with a version too small to refuse.',
  },
  {
    id: 'bystander',
    topic: 'psychology',
    title: 'The bystander effect',
    body: 'In early experiments, people were slower to help when others were present, since responsibility felt shared. Later studies of real CCTV footage found someone usually does step in.',
    tryThis: 'In an emergency, point at one person and ask them for help.',
  },
  {
    id: 'pratfall',
    topic: 'psychology',
    title: 'The pratfall effect',
    body: 'A competent person who makes a small, harmless mistake often becomes more likeable, not less (Aronson). Looking flawless can feel distant.',
    tryThis: 'Admit a small mistake openly today.',
  },
  {
    id: 'woop',
    topic: 'psychology',
    title: 'Wish, outcome, obstacle, plan',
    body: 'Gabriele Oettingen found that dreaming of a goal alone can sap effort, but pairing it with the obstacle in the way and a plan for it helps (WOOP).',
    tryThis: 'Name your wish, the best outcome, your main obstacle, and a when–then plan.',
  },

  // ---------- Software engineering ----------
  {
    id: 'work-right-fast',
    topic: 'software',
    title: 'Make it work, make it right, make it fast',
    body: 'In that order (Kent Beck). A working version shows you what the problem really is; cleaning it up comes next; speed matters only once you have measured where it is slow.',
    tryThis: 'Get the ugliest working version of your task done first.',
  },
  {
    id: 'premature-optimization',
    topic: 'software',
    title: 'Premature optimization',
    body: 'Knuth warned that optimizing too early causes much of the trouble in programming. Most time is spent in a small part of the code, and intuition about which part is usually wrong.',
    tryThis: 'Profile before you optimize anything.',
  },
  {
    id: 'yagni',
    topic: 'software',
    title: 'YAGNI',
    body: '"You aren\'t gonna need it": build for the requirements you have, not the ones you imagine. Speculative flexibility costs complexity now and is usually the wrong flexibility later.',
    tryThis: 'Delete one option, flag or parameter nothing uses.',
  },
  {
    id: 'wrong-abstraction',
    topic: 'software',
    title: 'Duplication beats the wrong abstraction',
    body: 'Merging code that only looks alike creates an abstraction that fights every later change (Sandi Metz). A common rule of thumb is to wait for the third copy before abstracting.',
    tryThis: 'Next time you see two similar functions, leave them until a third appears.',
  },
  {
    id: 'chestertons-fence',
    topic: 'software',
    title: "Chesterton's fence",
    body: "Don't remove a fence until you know why it was put up (G. K. Chesterton). Odd code often guards against a bug someone already hit.",
    tryThis: 'Check the history (git blame) before deleting code that looks pointless.',
  },
  {
    id: 'conways-law',
    topic: 'software',
    title: "Conway's law",
    body: "Systems end up mirroring the communication structure of the teams that build them. Three teams will tend to produce a three-part system, whether or not that's the right design.",
    tryThis: 'Look at your architecture diagram and your org chart side by side.',
  },
  {
    id: 'brooks-law',
    topic: 'software',
    title: "Brooks's law",
    body: 'Adding people to a late software project makes it later (Fred Brooks). Newcomers need onboarding, and every extra person adds communication paths.',
    tryThis: 'When behind, cut scope before adding people.',
  },
  {
    id: 'hofstadters-law',
    topic: 'software',
    title: "Hofstadter's law",
    body: "It always takes longer than you expect, even when you take Hofstadter's law into account. Unknowns are, by definition, missing from the estimate.",
    tryThis: 'Give ranges, not single numbers, when you estimate.',
  },
  {
    id: 'hyrums-law',
    topic: 'software',
    title: "Hyrum's law",
    body: 'With enough users, every observable behaviour of a system will be depended on by somebody, documented or not. Changing "internal" details can still break people.',
    tryThis: 'Treat error messages and ordering as part of your interface.',
  },
  {
    id: 'galls-law',
    topic: 'software',
    title: "Gall's law",
    body: 'A complex system that works has almost always evolved from a simple system that worked. Complex systems designed from scratch rarely work at all.',
    tryThis: 'Ship the smallest end-to-end version before adding features.',
  },
  {
    id: 'rubber-duck',
    topic: 'software',
    title: 'Rubber duck debugging',
    body: 'Explaining your code line by line, even to a rubber duck, often reveals the bug before you finish. Saying it out loud forces you to check what you assumed.',
    tryThis: 'Before asking for help, write the question out in full.',
  },
  {
    id: 'git-bisect',
    topic: 'software',
    title: 'Binary search for bugs',
    body: 'git bisect finds the commit that broke something by halving the range each step. A thousand commits take about ten tests.',
    tryThis: 'Next regression, run git bisect instead of reading diffs.',
  },
  {
    id: 'see-test-fail',
    topic: 'software',
    title: 'Watch the test fail',
    body: "A test you've never seen fail might not test anything. Writing it first, or breaking the code briefly, proves it can catch the bug.",
    tryThis: 'Break the code on purpose and check your new test goes red.',
  },
  {
    id: 'small-changes',
    topic: 'software',
    title: 'Small changes get real reviews',
    body: 'Reviewers find more problems in small changes; very large ones tend to get skimmed and approved. Small changes are also easier to revert.',
    tryThis: 'Split your next change so each part does one thing.',
  },
  {
    id: 'boy-scout',
    topic: 'software',
    title: 'The Boy Scout rule',
    body: 'Leave the code a little cleaner than you found it. Small, constant tidying keeps a codebase healthy without big rewrites.',
    tryThis: 'Rename one confusing variable in the file you touch today.',
  },
  {
    id: 'idempotency',
    topic: 'software',
    title: 'Make retries safe',
    body: 'An idempotent operation has the same effect whether it runs once or five times. Networks fail halfway, so anything that may be retried should be idempotent.',
    tryThis: 'Give each request an id so a repeat can be recognised and ignored.',
  },
  {
    id: 'parse-dont-validate',
    topic: 'software',
    title: "Parse, don't validate",
    body: 'Turn raw input into a type that can only hold valid data, once, at the edge (Alexis King). Then the rest of the code never has to check again.',
    tryThis: 'Replace a boolean check with a function that returns a stronger type.',
  },
  {
    id: 'least-astonishment',
    topic: 'software',
    title: 'Least astonishment',
    body: 'A component should behave the way most users would expect. If it surprises people, the design, not the users, is usually wrong.',
    tryThis: 'Watch someone use your feature without explaining it.',
  },
  {
    id: 'naming',
    topic: 'software',
    title: 'Two hard things',
    body: 'A well-known joke says the hard problems in computing are cache invalidation and naming things. A precise name is a small design decision; a vague one hides a muddled idea.',
    tryThis: 'If you cannot name a function well, ask whether it does two things.',
  },
  {
    id: 'big-o',
    topic: 'software',
    title: 'Feel the Big-O',
    body: 'A loop inside a loop over 10,000 items is 100 million steps. Fine for a list of 100, painful at a million: growth rate matters more than constant speed.',
    tryThis: 'Find one nested loop and ask how big its input can get.',
  },

  {
    id: 'kiss',
    topic: 'software',
    title: 'Keep it simple',
    body: 'Most systems work best when kept simple rather than made clever (KISS, often credited to the engineer Kelly Johnson). Simple things are easier to fix, change and hand over.',
    tryThis: "Remove one layer of indirection that isn't earning its keep.",
  },
  {
    id: 'separation-of-concerns',
    topic: 'software',
    title: 'Separation of concerns',
    body: 'Dijkstra argued for thinking about one aspect of a problem at a time. Code that keeps concerns apart, like data, logic and display, can change one without breaking the others.',
    tryThis: 'Find a function that mixes two jobs and split it.',
  },
  {
    id: 'law-of-demeter',
    topic: 'software',
    title: 'Talk to your neighbours',
    body: "The Law of Demeter says a piece of code should only talk to the things it directly holds. Long chains like a.b().c().d() tie you to details you don't own.",
    tryThis: 'Replace one long method chain with a single, well-named call.',
  },
  {
    id: 'postels-law',
    topic: 'software',
    title: 'Be strict in what you accept',
    body: "Postel's robustness principle said to be liberal in what you accept. Decades later, many argue it bred sloppy inputs that everyone must keep accepting; clear errors age better.",
    tryThis: 'Reject malformed input with a clear error instead of guessing.',
  },
  {
    id: 'fail-fast',
    topic: 'software',
    title: 'Fail fast',
    body: 'When something is wrong, stop at once and loudly, close to the cause. Code that limps on with bad data fails later, far away, in ways that are hard to trace.',
    tryThis: 'Add one assertion where a bad value would otherwise slip through.',
  },
  {
    id: 'pure-functions',
    topic: 'software',
    title: 'Pure functions',
    body: 'A function whose output depends only on its inputs, and which changes nothing else, is easy to test, reuse and reason about. Push side effects to the edges.',
    tryThis: 'Pull the calculation out of one function that also saves or prints.',
  },
  {
    id: 'leaky-abstractions',
    topic: 'software',
    title: 'Leaky abstractions',
    body: 'Joel Spolsky observed that every non-trivial abstraction leaks: the details it hides show through when things go wrong. You still need to understand one level down.',
    tryThis: 'Learn how one tool you rely on works underneath.',
  },
  {
    id: 'second-system',
    topic: 'software',
    title: 'The second-system effect',
    body: "Brooks warned that a team's second system is the most dangerous: freed from the first one's limits, they pile in every feature they held back.",
    tryThis: "When rewriting, list what you will leave out, not just what you'll add.",
  },
  {
    id: 'ninety-ninety',
    topic: 'software',
    title: 'The ninety-ninety rule',
    body: 'The first 90% of the code takes the first 90% of the time; the remaining 10% takes the other 90% (Tom Cargill). The last details are where time goes.',
    tryThis: 'Budget as much time for polish and edge cases as for the first version.',
  },
  {
    id: 'amdahls-law',
    topic: 'software',
    title: "Amdahl's law",
    body: "Speeding up part of a job can only help as much as that part matters. If 10% of the work can't be parallelised, no number of machines makes it more than ten times faster.",
    tryThis: "Measure what share of the time the part you're optimising really takes.",
  },
  {
    id: 'linus-law',
    topic: 'software',
    title: 'Many eyes',
    body: "Eric Raymond's \"Linus's law\" holds that with enough reviewers, every bug is shallow. Heartbleed, found in 2014 in widely used OpenSSL, showed that many users is not the same as many reviewers.",
    tryThis: "Ask for a review on the code you're least sure about.",
  },
  {
    id: 'semver',
    topic: 'software',
    title: 'Semantic versioning',
    body: 'In a version like 2.4.1, the first number changes for breaking changes, the second for new features, the third for fixes. It tells users what an upgrade may cost them.',
    tryThis: 'Check what a major version bump in a dependency actually breaks.',
  },
  {
    id: 'feature-flags',
    topic: 'software',
    title: 'Separate deploy from release',
    body: 'Feature flags let unfinished or risky code ship switched off, then turn on for a few users at a time. A bad change becomes a switch to flip, not a rollback.',
    tryThis: 'Put your next risky change behind a flag.',
  },
  {
    id: 'blameless-postmortems',
    topic: 'software',
    title: 'Blameless postmortems',
    body: 'After an outage, ask how the system let a reasonable person make the mistake, not who made it. People who fear blame hide the details you need.',
    tryThis: 'After the next mistake, ask what made it easy to make.',
  },
  {
    id: 'test-pyramid',
    topic: 'software',
    title: 'The test pyramid',
    body: 'Have many fast unit tests, fewer integration tests and a handful of end-to-end tests (Mike Cohn). Too many slow, broad tests make a suite that nobody runs.',
    tryThis: 'Turn one slow end-to-end check into a fast unit test.',
  },
  {
    id: 'flaky-tests',
    topic: 'software',
    title: 'Flaky tests are bugs',
    body: "A test that sometimes fails for no reason teaches everyone to ignore red. Soon a real failure gets ignored too. Fix it or delete it, don't just retry.",
    tryThis: 'Find your flakiest test and fix or remove it this week.',
  },
  {
    id: 'read-more-than-written',
    topic: 'software',
    title: 'Code is read far more than written',
    body: "Guido van Rossum's point, echoed in Python's style guide: code is read far more often than it is written. Optimise for the next reader, who may be you.",
    tryThis: 'Rewrite one clever line so a newcomer would understand it.',
  },
  {
    id: 'technical-debt',
    topic: 'software',
    title: 'Technical debt',
    body: 'Ward Cunningham compared shortcuts in code to borrowing money: fine to speed you up, as long as you pay it back. Left alone, the interest makes every change slower.',
    tryThis: 'Write down one shortcut you took, so it can be paid back.',
  },
  {
    id: 'kernighans-law',
    topic: 'software',
    title: 'Debugging is twice as hard',
    body: 'Kernighan noted that debugging is twice as hard as writing code, so if you write code as cleverly as you can, you are by definition not smart enough to debug it.',
    tryThis: 'Choose the plain version over the clever one.',
  },
  {
    id: 'timeouts',
    topic: 'software',
    title: 'Every call needs a timeout',
    body: 'A network call without a timeout can wait forever, and one stuck call can tie up a whole service. Decide how long is too long, and what to do then.',
    tryThis: 'Find one network call in your code and check it has a timeout.',
  },

  // ---------- Philosophy ----------
  {
    id: 'dichotomy-of-control',
    topic: 'philosophy',
    title: 'The dichotomy of control',
    body: 'Epictetus split the world into what is up to us (our judgments and actions) and what is not (everything else). Peace comes from putting effort only into the first.',
    tryThis: 'Sort one worry into what you control and what you don’t.',
  },
  {
    id: 'obstacle-way',
    topic: 'philosophy',
    title: 'The obstacle becomes the way',
    body: 'Marcus Aurelius wrote that what blocks an action can itself become a path for acting well. A setback is a chance to practise patience, courage or skill.',
    tryThis: 'Ask what today’s annoyance lets you practise.',
  },
  {
    id: 'premeditatio',
    topic: 'philosophy',
    title: 'Rehearse what could go wrong',
    body: 'The Stoics imagined losses and setbacks in advance, so they would hurt less and find them ready. Modern teams do the same in a "pre-mortem".',
    tryThis: 'Before a plan starts, list three ways it could fail.',
  },
  {
    id: 'memento-mori',
    topic: 'philosophy',
    title: 'Memento mori',
    body: 'Remember that you will die. For the Stoics this was not gloom but focus: it makes trivial things shrink and important ones clear.',
    tryThis: 'Ask whether today’s biggest worry will matter in five years.',
  },
  {
    id: 'shortness-of-life',
    topic: 'philosophy',
    title: 'On the shortness of life',
    body: 'Seneca argued that life is long enough if we use it well; we make it short by giving our time away carelessly. People guard their money but hand out their hours.',
    tryThis: 'Notice one hour this week you gave away without choosing to.',
  },
  {
    id: 'occams-razor',
    topic: 'philosophy',
    title: "Occam's razor",
    body: 'When two explanations fit the facts, prefer the one that assumes less. It is a rule for where to look first, not proof that the simple answer is right.',
    tryThis: 'Next time something breaks, check the most boring cause first.',
  },
  {
    id: 'hanlons-razor',
    topic: 'philosophy',
    title: "Hanlon's razor",
    body: 'Never attribute to malice what can be adequately explained by carelessness. Most slights are accidents; assuming so keeps you calm and usually right.',
    tryThis: 'Reread an annoying message assuming the sender was simply rushed.',
  },
  {
    id: 'socratic-ignorance',
    topic: 'philosophy',
    title: 'Socratic ignorance',
    body: 'Socrates was said to be wise only because he knew that he did not know. His method was to keep asking questions until hidden assumptions came into view.',
    tryThis: 'Ask "how do I know that?" about one thing you are sure of.',
  },
  {
    id: 'charity',
    topic: 'philosophy',
    title: 'The principle of charity',
    body: 'Interpret an argument in its strongest, most reasonable form before you answer it ("steelmanning"). Beating a weak version teaches you nothing.',
    tryThis: 'Restate someone’s view until they agree you got it right.',
  },
  {
    id: 'golden-mean',
    topic: 'philosophy',
    title: 'The golden mean',
    body: 'Aristotle saw each virtue as a middle between two vices: courage between cowardice and recklessness, generosity between stinginess and waste.',
    tryThis: 'Pick a trait you value and name its two extremes.',
  },
  {
    id: 'virtue-habit',
    topic: 'philosophy',
    title: 'Character is practised',
    body: 'Aristotle argued that we become brave by doing brave things and fair by doing fair things. Virtue is less a feeling than a habit built by repetition.',
    tryThis: 'Do one small act today of the person you want to become.',
  },
  {
    id: 'categorical-imperative',
    topic: 'philosophy',
    title: 'Could everyone do it?',
    body: 'Kant proposed acting only on rules you could want everyone to follow, and never treating people merely as tools. If an act only works because others don’t do it, suspect it.',
    tryThis: 'Test a shortcut: what if everyone took it?',
  },
  {
    id: 'utilitarianism',
    topic: 'philosophy',
    title: 'The greatest good',
    body: 'Bentham and Mill judged actions by their consequences for everyone’s wellbeing. Its power is its fairness; its critics ask what it permits against a few.',
    tryThis: 'For a decision, list everyone it affects, not just you.',
  },
  {
    id: 'veil-of-ignorance',
    topic: 'philosophy',
    title: 'The veil of ignorance',
    body: 'Rawls asked what rules you would choose for society if you did not know who you would be in it: rich or poor, healthy or sick. It is a test for fairness.',
    tryThis: 'Judge a rule at work as if you might be on its losing side.',
  },
  {
    id: 'is-ought',
    topic: 'philosophy',
    title: 'Is and ought',
    body: 'Hume noticed that arguments slide from how things are to how they ought to be without justifying the step. Facts alone never settle what we should do.',
    tryThis: 'Spot the hidden "should" in an argument that only lists facts.',
  },
  {
    id: 'ship-of-theseus',
    topic: 'philosophy',
    title: 'The ship of Theseus',
    body: 'If every plank of a ship is replaced one at a time, is it still the same ship? The puzzle asks what makes anything, including a person, stay itself through change.',
    tryThis: 'Think of how much of you has changed in ten years, and what hasn’t.',
  },
  {
    id: 'heraclitus-river',
    topic: 'philosophy',
    title: 'The same river',
    body: 'Heraclitus held that everything flows: you cannot step into the same river twice, for both it and you have changed. Stability is a slow kind of change.',
    tryThis: 'Revisit something you once judged, and see it with today’s eyes.',
  },
  {
    id: 'sisyphus',
    topic: 'philosophy',
    title: 'Sisyphus, happy',
    body: 'Camus pictured Sisyphus pushing his rock forever and concluded we must imagine him happy. Meaning is not found at the top but made in the pushing.',
    tryThis: 'Find one thing to enjoy in a task you repeat every day.',
  },
  {
    id: 'amor-fati',
    topic: 'philosophy',
    title: 'Amor fati',
    body: 'Nietzsche urged loving your fate: not just putting up with what happens, but wanting it to be as it is. The Stoics held a gentler version, accepting what comes.',
    tryThis: 'Name one past setback that led somewhere you are glad to be.',
  },
  {
    id: 'pascal-room',
    topic: 'philosophy',
    title: 'Sitting quietly in a room',
    body: 'Pascal thought much human misery comes from being unable to sit quietly in a room alone. We chase distraction to avoid our own thoughts.',
    tryThis: 'Spend two minutes of this ride just looking out of the window.',
  },
  {
    id: 'plato-cave',
    topic: 'philosophy',
    title: 'The allegory of the cave',
    body: 'Plato imagined prisoners who see only shadows on a wall and take them for reality. The freed prisoner who sees the sun finds it painful, and is mocked when he returns.',
    tryThis: 'Ask what "shadow" you might be mistaking for the whole picture.',
  },
  {
    id: 'cogito',
    topic: 'philosophy',
    title: 'I think, therefore I am',
    body: 'Descartes doubted everything he could, looking for one certainty. He found that the very act of doubting proved that he, the doubter, existed.',
    tryThis: 'Pick a belief and ask what you would still be sure of if it were wrong.',
  },
  {
    id: 'problem-of-induction',
    topic: 'philosophy',
    title: 'The problem of induction',
    body: "Hume pointed out that no number of past sunrises logically proves the sun will rise tomorrow. We rely on patterns continuing, but can't prove that they will.",
    tryThis: 'Name an assumption you make only because it has always held so far.',
  },
  {
    id: 'falsifiability',
    topic: 'philosophy',
    title: 'Falsifiability',
    body: 'Karl Popper held that a theory is scientific only if some observation could prove it wrong. A claim that fits every possible outcome explains nothing.',
    tryThis: 'Ask of a strong opinion: what would prove me wrong?',
  },
  {
    id: 'paradigm-shifts',
    topic: 'philosophy',
    title: 'Paradigm shifts',
    body: "Thomas Kuhn argued that science doesn't only grow step by step; now and then a whole framework is replaced, like Earth-centred astronomy giving way to a Sun-centred one.",
    tryThis: 'Notice an assumption your field takes for granted.',
  },
  {
    id: 'limits-of-language',
    topic: 'philosophy',
    title: 'The limits of language',
    body: 'Wittgenstein wrote that the limits of his language meant the limits of his world. What we have words for, we can notice and think about more easily.',
    tryThis: "Learn the precise word for something you feel but can't name.",
  },
  {
    id: 'epicurus',
    topic: 'philosophy',
    title: 'Epicurus on pleasure',
    body: 'Epicurus taught that a good life is simple: friends, freedom and thought, with little pain or fear. He argued that death is nothing to us, since where death is, we are not.',
    tryThis: "List three simple pleasures you already have and don't notice.",
  },
  {
    id: 'eudaimonia',
    topic: 'philosophy',
    title: 'Eudaimonia',
    body: "Aristotle's word for the good life means flourishing, not a feeling of happiness. It comes from using your best capacities well, over a whole life.",
    tryThis: 'Spend part of today doing something you are good at and care about.',
  },
  {
    id: 'confucius-reciprocity',
    topic: 'philosophy',
    title: 'What you would not want',
    body: 'Confucius put the golden rule negatively: do not do to others what you would not want done to yourself. It asks less than love, and is harder to argue with.',
    tryThis: 'Before sending a sharp reply, imagine receiving it.',
  },
  {
    id: 'wu-wei',
    topic: 'philosophy',
    title: 'Wu wei',
    body: 'Laozi praised effortless action: like water, which is soft and yields yet wears away stone. Pushing against the grain wastes effort; working with it goes further.',
    tryThis: 'Find a task you are forcing and look for the easier grain.',
  },
  {
    id: 'impermanence',
    topic: 'philosophy',
    title: 'Impermanence',
    body: "The Buddha taught that everything changes, and that suffering comes from craving and clinging to what can't last. Loosening the grip eases the pain.",
    tryThis: 'Notice one thing you are clinging to, and hold it more lightly.',
  },
  {
    id: 'existence-precedes-essence',
    topic: 'philosophy',
    title: 'Existence precedes essence',
    body: "Sartre argued that people aren't born with a fixed nature: we exist first and define ourselves by our choices. That freedom brings full responsibility.",
    tryThis: "Pick one \"that's just how I am\" and treat it as a choice.",
  },
  {
    id: 'beauvoir',
    topic: 'philosophy',
    title: 'One becomes',
    body: 'Simone de Beauvoir argued that one is not born a woman but becomes one: much of what we take as natural in who we are is shaped by society and upbringing.',
    tryThis: 'Ask where one of your "natural" habits actually came from.',
  },
  {
    id: 'harm-principle',
    topic: 'philosophy',
    title: 'The harm principle',
    body: "Mill argued that the only good reason to limit someone's freedom against their will is to prevent harm to others. Their own good is not reason enough.",
    tryThis: "Next time you judge someone's choice, ask who it actually harms.",
  },
  {
    id: 'trolley-problem',
    topic: 'philosophy',
    title: 'The trolley problem',
    body: 'Philippa Foot asked whether you should divert a runaway trolley to kill one person instead of five. Most say yes; far fewer would push someone to stop it. Why the difference?',
    tryThis: 'Ask what matters to you beyond outcomes: intentions, rights, or both.',
  },
  {
    id: 'map-territory',
    topic: 'philosophy',
    title: 'The map is not the territory',
    body: 'Alfred Korzybski warned against confusing our models with reality. Every map leaves things out; problems start when we forget what it leaves out.',
    tryThis: 'Find a plan or metric you treat as if it were the real thing.',
  },
  {
    id: 'frankl-meaning',
    topic: 'philosophy',
    title: 'The last freedom',
    body: 'Viktor Frankl, who survived the Nazi camps, wrote that when everything else is taken, we can still choose our attitude. Those with a reason to live endured more.',
    tryThis: 'In a hard moment today, choose the attitude you want to meet it with.',
  },
  {
    id: 'kierkegaard-backwards',
    topic: 'philosophy',
    title: 'Lived forwards',
    body: "Kierkegaard observed that life can only be understood backwards, but must be lived forwards. We never have the clarity we'll have later when we choose.",
    tryThis: 'Make one decision today without waiting for certainty.',
  },
  {
    id: 'russells-teapot',
    topic: 'philosophy',
    title: "Russell's teapot",
    body: 'Bertrand Russell imagined a teapot orbiting the Sun, too small to see. No one could disprove it, yet the burden of proof lies on whoever claims it, not on the doubters.',
    tryThis: "When someone says \"prove it isn't so\", ask them to prove it is.",
  },
  {
    id: 'seneca-imagination',
    topic: 'philosophy',
    title: 'Suffering in imagination',
    body: 'Seneca wrote to a friend that we are more often frightened than hurt, and suffer more in imagination than in reality. Many feared things never happen.',
    tryThis: 'Write down one worry, then check next week whether it happened.',
  },

  // ---------- Productivity ----------
  {
    id: 'eisenhower-matrix',
    topic: 'productivity',
    title: 'Urgent is not important',
    body: 'Sort tasks by two questions: is it urgent, and is it important? The Eisenhower matrix says to do the important-and-urgent, schedule the important-not-urgent, and delegate or drop the rest.',
    tryThis: "Put today's list into the four boxes and drop one task.",
  },
  {
    id: 'pomodoro',
    topic: 'productivity',
    title: 'The Pomodoro Technique',
    body: "Francesco Cirillo's method: work on one thing for 25 minutes, then rest for 5, and take a longer break after four rounds. A short, fixed stretch makes starting easier.",
    tryThis: "Set a 25-minute timer for the task you're avoiding.",
  },
  {
    id: 'parkinsons-law',
    topic: 'productivity',
    title: "Parkinson's law",
    body: 'Work expands to fill the time available for its completion (C. Northcote Parkinson, 1955). Give a task a week and it will take a week.',
    tryThis: "Give your next task half the time you'd normally allow.",
  },
  {
    id: 'eat-the-frog',
    topic: 'productivity',
    title: 'Eat the frog',
    body: 'Do the hardest, most dreaded task first, before the day fills up (popularised by Brian Tracy). Everything after it feels lighter.',
    tryThis: 'Tomorrow, start with the task you most want to put off.',
  },
  {
    id: 'two-minute-rule',
    topic: 'productivity',
    title: 'The two-minute rule',
    body: "In David Allen's Getting Things Done: if something takes less than two minutes, do it now. Tracking it would take longer than doing it.",
    tryThis: 'Clear every two-minute task sitting in your inbox.',
  },
  {
    id: 'capture',
    topic: 'productivity',
    title: 'Your mind is for having ideas',
    body: "David Allen's line: the mind is for having ideas, not holding them. Every open loop kept in your head nags at you; one trusted list lets you let go.",
    tryThis: 'Write down every open task in your head right now.',
  },
  {
    id: 'next-action',
    topic: 'productivity',
    title: 'Define the next action',
    body: "\"Plan the trip\" is a project; \"text Sam about dates\" is a next action. Vague tasks get avoided because the first step isn't clear (Getting Things Done).",
    tryThis: 'Rewrite one vague task as the very next physical step.',
  },
  {
    id: 'weekly-review',
    topic: 'productivity',
    title: 'The weekly review',
    body: "Once a week, go through every list, calendar and project, and decide what's next for each. Without a review, a to-do list slowly stops being trusted.",
    tryThis: "Book 30 minutes this week to review everything you're committed to.",
  },
  {
    id: 'time-blocking',
    topic: 'productivity',
    title: 'Time blocking',
    body: "Instead of a to-do list alone, give each task a slot on the calendar (Cal Newport). A list says what; a block says when, and shows what won't fit.",
    tryThis: 'Block out tomorrow morning for the one task that matters most.',
  },
  {
    id: 'deep-work',
    topic: 'productivity',
    title: 'Deep work',
    body: "Cal Newport's term for focused work on something hard, free of distraction. It produces most of the value, and it is being crowded out by shallow tasks like email.",
    tryThis: 'Protect one distraction-free hour a day for your hardest work.',
  },
  {
    id: 'makers-schedule',
    topic: 'productivity',
    title: "Maker's and manager's schedules",
    body: 'Paul Graham noted that managers work in hour slots, but makers need half days: one meeting in the middle of an afternoon can break it into pieces too small for real work.',
    tryThis: 'Cluster your meetings together to leave long unbroken blocks.',
  },
  {
    id: 'pareto',
    topic: 'productivity',
    title: 'The 80/20 principle',
    body: "A small share of causes often drives most of the results: a few customers, features or habits. It's a rough pattern, not a law, but it points to where to look.",
    tryThis: 'Find the 20% of your tasks that produce most of what matters.',
  },
  {
    id: 'batching',
    topic: 'productivity',
    title: 'Batch small tasks',
    body: 'Replies, errands and admin go faster done together than scattered across the day, since each switch has a cost.',
    tryThis: 'Save small tasks for one batch at a set time today.',
  },
  {
    id: 'multitasking',
    topic: 'productivity',
    title: 'Multitasking is switching',
    body: "For demanding tasks, the brain doesn't really do two at once; it switches between them, losing time and accuracy at each switch.",
    tryThis: 'Close every tab and app except the one you need.',
  },
  {
    id: 'progress-principle',
    topic: 'productivity',
    title: 'The progress principle',
    body: "Teresa Amabile found that of everything that lifts people's motivation at work, making progress on meaningful work matters most, even small steps.",
    tryThis: 'At the end of the day, write down what you moved forward.',
  },
  {
    id: 'timeboxing',
    topic: 'productivity',
    title: 'Timeboxing',
    body: "Fix the time, not the scope: decide you'll spend 45 minutes and stop there. It limits perfectionism and makes open-ended work finish.",
    tryThis: 'Give your next open-ended task a fixed time and stop when it ends.',
  },
  {
    id: 'opportunity-cost',
    topic: 'productivity',
    title: 'Every yes is a no',
    body: 'Time spent on one thing is time not spent on another: its opportunity cost. A new commitment should be worth more than what it pushes out.',
    tryThis: "Before saying yes, name what you'll give up to make room.",
  },
  {
    id: 'peak-energy',
    topic: 'productivity',
    title: 'Match work to energy',
    body: 'Most people have hours when they think most sharply, often in the morning. Hard work fits there; routine tasks can fill the dips.',
    tryThis: 'Notice when you think best and save it for your hardest task.',
  },
  {
    id: 'breaks-restore',
    topic: 'productivity',
    title: 'Breaks restore attention',
    body: 'Focus wears down with use, and short breaks, especially a walk or time outdoors, help restore it (attention restoration theory). Scrolling a phone rests it less.',
    tryThis: 'Take your next break away from a screen.',
  },
  {
    id: 'email-batches',
    topic: 'productivity',
    title: 'Check email less often',
    body: 'In one study, people who checked email only three times a day felt less stressed than those who checked freely, and got as much done (Kushlev and Dunn).',
    tryThis: 'Check messages at three set times tomorrow and close them in between.',
  },
  {
    id: 'phone-away',
    topic: 'productivity',
    title: 'Out of sight, out of mind',
    body: "Some studies found that a phone merely lying on the desk lowers people's performance on hard tasks, even switched off. Findings are mixed, but distance costs nothing.",
    tryThis: 'Put your phone in another room while you focus.',
  },
  {
    id: 'five-minute-start',
    topic: 'productivity',
    title: 'Just start for five minutes',
    body: 'Starting is often the hardest part. Committing to only five minutes lowers the barrier, and once going, most people keep going.',
    tryThis: "Do five minutes of the task you're avoiding, then decide.",
  },
  {
    id: 'procrastination-mood',
    topic: 'productivity',
    title: 'Procrastination is about mood',
    body: 'Researchers like Tim Pychyl and Fuschia Sirois see procrastination as avoiding bad feelings about a task, not laziness. Students who forgave themselves procrastinated less later.',
    tryThis: 'Name the feeling the task gives you, then start anyway.',
  },
  {
    id: 'goal-gradient',
    topic: 'productivity',
    title: 'The goal-gradient effect',
    body: 'Effort speeds up as a goal gets closer. Coffee-card customers bought faster as they neared a free drink, even when given a head start (Kivetz).',
    tryThis: 'Break a long goal into short stages, each with its own finish line.',
  },
  {
    id: 'checklists',
    topic: 'productivity',
    title: 'Use checklists',
    body: 'Atul Gawande showed that simple checklists save lives: a WHO surgical checklist cut deaths and complications in hospitals. Experts forget routine steps too.',
    tryThis: 'Write a checklist for a task you repeat and sometimes get wrong.',
  },
  {
    id: 'most-important-tasks',
    topic: 'productivity',
    title: 'Most important tasks',
    body: 'Pick one to three tasks that would make the day a success, and do them before anything else. A long list hides what really matters.',
    tryThis: "Choose tomorrow's one to three most important tasks tonight.",
  },
  {
    id: 'ivy-lee',
    topic: 'productivity',
    title: 'The Ivy Lee method',
    body: 'From a story of 1918: each evening, write down the six most important tasks for tomorrow, in order. Work through them one at a time, and move any left over to the next list.',
    tryThis: 'Try it tonight: six tasks, ranked, for tomorrow.',
  },
  {
    id: 'decision-fatigue',
    topic: 'productivity',
    title: 'Fewer trivial decisions',
    body: 'Making many decisions may wear down the quality of later ones, though the evidence is debated. Routines for small choices, like meals or clothes, save effort for big ones.',
    tryThis: 'Turn one daily small decision into a fixed routine.',
  },
  {
    id: 'write-to-think',
    topic: 'productivity',
    title: 'Writing is thinking',
    body: "Writing an idea out forces vague thoughts into sentences, and shows where they don't hold up. Many writers say they write to find out what they think.",
    tryThis: 'Write a paragraph about a problem before discussing it.',
  },
  {
    id: 'pre-commitment',
    topic: 'productivity',
    title: 'Tie yourself to the mast',
    body: 'Ulysses had himself tied to the mast to hear the Sirens without steering towards them. Deciding in advance, and removing the option later, beats relying on willpower.',
    tryThis: "Remove the temptation now, while you're calm.",
  },
  {
    id: 'friction',
    topic: 'productivity',
    title: 'Add friction to bad habits',
    body: 'Small barriers change behaviour: a few seconds of extra effort can stop a bad habit, and removing a few can start a good one.',
    tryThis: 'Log out of one distracting app, and lay out what you need for a good habit.',
  },
  {
    id: 'satisficing',
    topic: 'productivity',
    title: 'Good enough is often best',
    body: 'Herbert Simon coined "satisficing": choosing the first option that meets your standards. Barry Schwartz found people who always seek the best option are often less satisfied.',
    tryThis: 'Set a "good enough" bar for a choice, and take the first option that meets it.',
  },
  {
    id: 'two-way-doors',
    topic: 'productivity',
    title: 'One-way and two-way doors',
    body: 'Jeff Bezos split decisions into reversible and irreversible ones. Reversible ones should be made fast by few people; only the irreversible deserve slow care.',
    tryThis: "Ask of a decision you're stuck on: can I undo this?",
  },
  {
    id: 'perfect-good',
    topic: 'productivity',
    title: 'The perfect is the enemy of the good',
    body: "Voltaire's point: waiting for perfect can mean shipping nothing. A good version now teaches you more than a perfect one that never arrives.",
    tryThis: 'Finish one thing today at "good" instead of polishing it.',
  },
  {
    id: 'long-hours',
    topic: 'productivity',
    title: 'Long hours have limits',
    body: 'A study of munitions workers found output per hour fell sharply past about 50 hours a week; those working 70 produced little more than those working 55 (Pencavel).',
    tryThis: 'Stop at a fixed time today and see what changes.',
  },
  {
    id: 'sleep-impairment',
    topic: 'productivity',
    title: 'Tired is like tipsy',
    body: 'After 17 to 19 hours awake, people perform about as badly as with a legal-limit blood alcohol level, one study found. Late-night work is often slow work.',
    tryThis: 'Stop working when you catch yourself rereading the same line.',
  },
  {
    id: 'shutdown-ritual',
    topic: 'productivity',
    title: 'A shutdown ritual',
    body: "Cal Newport ends each workday with a set routine: check the lists, plan tomorrow, then say it's done. It lets the mind stop working after hours.",
    tryThis: "End today by writing tomorrow's plan, then call it done.",
  },
  {
    id: 'big-rocks',
    topic: 'productivity',
    title: 'Big rocks first',
    body: "Stephen Covey's image: fill a jar with sand and pebbles first, and the big rocks won't fit; put the big rocks in first, and the rest fills in around them.",
    tryThis: "Schedule this week's big rock before anything else.",
  },
  {
    id: 'kaizen',
    topic: 'productivity',
    title: 'Small improvements add up',
    body: 'Kaizen, from Japanese manufacturing, means continuous improvement in small steps. Tiny changes are easy to start and, kept up, add up to large ones.',
    tryThis: 'Make one small improvement to how you work today.',
  },
  {
    id: 'done-list',
    topic: 'productivity',
    title: 'Keep a done list',
    body: 'A list of what you finished shows progress a to-do list hides, and makes it easier to see where the time actually went.',
    tryThis: 'Write down everything you completed today.',
  },
];

/**
 * The next card to show: one not yet seen from the chosen topics, picked with `random`
 * (0 to 1). Once all of them are seen, those topics start over. `prefer` narrows it to
 * one topic, if that topic is chosen: the one the solved picture belongs to. Returns the
 * card and the new list of seen ids; null when no topic is chosen.
 */
export function pickKnowledge(
  topics: readonly Topic[],
  seen: readonly string[],
  random: number,
  prefer?: Topic,
): { id: string; seen: string[] } | null {
  const from = prefer && topics.includes(prefer) ? [prefer] : topics;
  const deck = KNOWLEDGE.filter((k) => from.includes(k.topic));
  if (deck.length === 0) return null;
  const seenSet = new Set(seen);
  let fresh = deck.filter((k) => !seenSet.has(k.id));
  let kept = [...seen];
  if (fresh.length === 0) {
    // Round done: forget these topics' cards, keep the others' history.
    const inDeck = new Set(deck.map((k) => k.id));
    kept = kept.filter((id) => !inDeck.has(id));
    fresh = deck;
  }
  const card = fresh[Math.min(fresh.length - 1, Math.floor(random * fresh.length))];
  return { id: card.id, seen: [...kept, card.id] };
}

export const knowledgeById = (id: string) => KNOWLEDGE.find((k) => k.id === id);
